NFDeployment Kpt function changes
nephio-project/nephio pull request #418
Opened 2023-10-18 20:39 UTC by aakashchan

1. Updated the Nf Deploy Fn to use latest API changes by removing older generics code.
2. Removed reference to all the older APIs in testdata including other functions
3. Added tests for dependency test cases. 

Tests Run
1.   Executed all pipeline tests - *Pass*
2.  Executed dependency tests for single and multiple - *Pass*
3.  Execute all functions unite tests - *Pass*
4.  Docker build  - *Pass*

Docker image for testing - `docker.io/lostbrain/nfdeployfn:test-1`

2023-10-18 20:43 UTC, aakashchan commented
Notes: 

1. I am not able to replicate the multiple duplicate config entries bug  @arora-sagar So didn't want to add duplicate removal code in kpt function without finding the root cause.

2. Not able to reproduce the same name for multiple dependencies. Have added that tests too, you can verify the expected data. @josephthaliath 

3. Assumption is provider field will be present in base package and also have not added validation for the same. @henderiw

2023-10-18 20:50 UTC, aakashchan commented
/hold

2023-10-22 05:01 UTC, henderiw commented
update the go mod files for all the fns to include the latest api. This will solve some test failures

2023-10-22 05:08 UTC, henderiw commented
The one thing I see and this is a discussion. Since we allow for parameterRefs to be present from the beginning. Should we do the same for interfaces, dnns, etc ?

This allows the package builder to add things statically w/o the need for specialization ?

2023-10-24 12:42 UTC, josephthaliath commented
Thanks @aakashchan for checking the multiple dependencies. I think it was an issue on our side. Just wanted to check if we can add ParametersRef statically in the package, will krm function overwrite this while generating parameterRefs for dependencies added.

2023-10-27 19:07 UTC, henderiw requested changes

2023-10-27 19:07 UTC, henderiw commented on krm-functions/nfdeploy-fn/README.md
> +    - This resource is the source of truth for the capacity details in NFDeployment spec.
add the DependencyKind as well here

2023-10-29 18:17 UTC, henderiw commented
/lgtm

2023-11-01 02:59 UTC, gvbalaji commented
Looks like this PR is approved but needs a rebase @aakashchan

2023-11-01 07:55 UTC, aakashchan commented
> Looks like this PR is approved but needs a rebase @aakashchan

Yes, done. We are good to merge now. Thanks @gvbalaji

2023-11-01 11:22 UTC, henderiw commented
/lgtm
/approve

2023-11-01 11:22 UTC, merged