interface-fn
nephio-project/nephio pull request #69
Opened 2023-03-30 06:03 UTC by henderiw

interface-fn is a function in Nephio R1 that operates on the interface requirement CR. It performs CRUD operation in the package on the NAD, VLANALlocation and IP Allocation resources.

2023-04-07 03:08 UTC, gvbalaji commented
@henderiw thanks. I understand this will change once the function runtime library and it's client intarface are finalized and merged. If my understanding is correct, can you please convert this into a draft PR?

2023-05-02 11:13 UTC, kispaljr commented
@henderiw I believe you failing gosec test can be solved by go workspaces (as You suggested on Slack :) )
This is how I did it with dnn-fn: https://github.com/nephio-project/nephio/pull/70, notice the go.work file in root of the repo.

2023-05-02 11:27 UTC, kispaljr approved these changes
As I only have cosmetic comments, This looks good to me even in it current state

2023-05-02 11:27 UTC, kispaljr commented on krm-functions/interface-fn/mutator.go
> +	clusterKOE, err := kubeobject.NewFromKubeObject[*infrav1alpha1.ClusterContext](o)
This comment is just a reminder for a potential need for change in the future:
As I wrote on Slack we should decide whether to use pointer or struct type parameters of KubeObjectExt.
If the decision will be pointers, than no comment here, otherwise the code here and other places should be aligned to the decision.

2023-05-02 11:27 UTC, kispaljr commented on krm-functions/interface-fn/mutator.go
> +			//alloc, err := ko.NewFromKubeObject[*vlanv1alpha1.VLANAllocation](vlanalloc)
this comment is not needed any more

2023-05-02 11:27 UTC, kispaljr commented
/lgtm

2023-05-04 20:52 UTC, kispaljr commented
/retest presubmit-nephio-go-test

2023-05-04 20:53 UTC, kispaljr commented
/test presubmit-nephio-go-test

2023-05-04 21:13 UTC, kispaljr requested changes
Nested go.mod files bites us again:
presubmit-nephio-go-test  doesn't run any tests inside `krm-functions/interface-fn` at all.
Actually since the new (not backward compatible) KubeObjectExt API was merged into this branch, this code doesn't even compile, and none of our presubmit tests detected this :(
I've left comments for the quick changes required for the code to compile, otherwise this LGTM

2023-05-04 21:13 UTC, kispaljr commented on krm-functions/interface-fn/fn/function.go
> +	err = itfceKOE.SetStatus(itfce.Status)
With the new API this should be:
`itfceKOE.SetStatus(itfce)`

2023-05-05 23:48 UTC, gvbalaji commented
Thanks  @henderiw . A rebase is needed for this PR.

2023-05-08 13:08 UTC, kispaljr commented
/lgtm

2023-05-08 13:37 UTC, merged